/** @format */

"use client";

import { Plus, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/shared/inputs/input";
import { TableShell } from "@/components/shared/data-display/TableShell";
import { Textarea } from "@/components/shared/inputs/textarea";

import {
  INITIAL_INVOICE_DRAFT,
  INITIAL_INVOICE_LINE_ITEM,
} from "../../constants/invoicing-ar-initial-state";
import type { InvoiceLineItem } from "../../types/invoicing-ar";

export type FeatureCreateInvoiceSubmitPayload = {
  customer_query: string;
  invoice_date: string;
  due_date: string;
  notes: string;
  line_items: InvoiceLineItem[];
};

type FeatureCreateInvoiceFormProps = {
  onCancel?: () => void;
  onSubmit?: (payload: FeatureCreateInvoiceSubmitPayload) => void;
  submitLabel?: string;
  isSubmitting?: boolean;
  errorMessage?: string | null;
  invoiceNumberPreview?: string;
  customerOptions?: string[];
  productOptions?: string[];
};

const EMPTY_CUSTOMER_OPTIONS: string[] = [];
const EMPTY_PRODUCT_OPTIONS: string[] = [];

export function FeatureCreateInvoiceForm({
  onCancel,
  onSubmit,
  submitLabel = "Create Invoice",
  isSubmitting = false,
  errorMessage,
  invoiceNumberPreview = "Auto-generated by system",
  customerOptions = EMPTY_CUSTOMER_OPTIONS,
  productOptions = EMPTY_PRODUCT_OPTIONS,
}: FeatureCreateInvoiceFormProps) {
  const [customerQuery, setCustomerQuery] = useState(
    INITIAL_INVOICE_DRAFT.customer_query,
  );
  const [invoiceDate, setInvoiceDate] = useState(
    INITIAL_INVOICE_DRAFT.invoice_date,
  );
  const [dueDate, setDueDate] = useState(INITIAL_INVOICE_DRAFT.due_date);
  const [notes, setNotes] = useState(INITIAL_INVOICE_DRAFT.internal_notes);
  const [lineItems, setLineItems] = useState<InvoiceLineItem[]>(
    INITIAL_INVOICE_DRAFT.line_items,
  );

  const totals = useMemo(() => {
    const subtotal = lineItems.reduce((sum, row) => {
      const normalized = Number(row.price.replaceAll(",", "")) || 0;
      return sum + row.qty * normalized;
    }, 0);

    const tax = lineItems.reduce((sum, row) => {
      const normalized = Number(row.price.replaceAll(",", "")) || 0;
      const base = row.qty * normalized;
      const taxPercent = Number(row.tax.replace(/[^\d.-]/g, "")) || 0;
      return sum + base * (taxPercent / 100);
    }, 0);
    const grandTotal = subtotal + tax;

    return {
      subtotal: subtotal.toLocaleString("id-ID"),
      tax: tax.toLocaleString("id-ID"),
      grandTotal: grandTotal.toLocaleString("id-ID"),
    };
  }, [lineItems]);

  const addLineItem = () => {
    setLineItems((current) => [
      ...current,
      {
        ...INITIAL_INVOICE_LINE_ITEM,
        id: `line-${Date.now()}`,
      },
    ]);
  };

  const updateLineItem = (
    id: string,
    key: keyof InvoiceLineItem,
    value: string | number,
  ) => {
    setLineItems((current) =>
      current.map((row) => {
        if (row.id !== id) return row;
        return {
          ...row,
          [key]: value,
        };
      }),
    );
  };

  const removeLineItem = (id: string) => {
    setLineItems((current) =>
      current.length > 1 ? current.filter((row) => row.id !== id) : current,
    );
  };

  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    onSubmit?.({
      customer_query: customerQuery,
      invoice_date: invoiceDate,
      due_date: dueDate,
      notes,
      line_items: lineItems,
    });
  };

  return (
    <form onSubmit={handleSubmit} data-testid="accounting-ar-invoice-create-form">
      <Card className="border-gray-200 shadow-sm dark:border-gray-700">
        <CardContent className="space-y-8 p-6">
          <div className="flex items-center justify-between border-b border-gray-200 pb-4 dark:border-gray-700">
            <div className="flex items-center gap-3">
              <div className="rounded-lg bg-indigo-50 p-2 text-indigo-600 dark:bg-indigo-900/40 dark:text-indigo-400">
                <Plus className="h-5 w-5" />
              </div>
              <div>
                <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                  Create New Invoice
                </h2>
                <p className="text-xs text-gray-500 dark:text-gray-400">
                  Generate a new customer billing statement
                </p>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 gap-6 md:grid-cols-4">
            <div className="md:col-span-2">
              <label
                htmlFor="invoice-create-customer"
                className="mb-1.5 block text-sm font-semibold text-gray-700 dark:text-gray-300"
              >
                Customer
              </label>
              <div className="relative">
                <Search className="pointer-events-none absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-gray-400" />
                <Input
                  id="invoice-create-customer"
                  value={customerQuery}
                  onChange={(event) => setCustomerQuery(event.target.value)}
                  data-testid="accounting-ar-invoice-customer-input"
                  placeholder="Search customer..."
                  className="bg-gray-50 pl-10 dark:bg-gray-800"
                  list="invoice-customer-options"
                />
                {customerOptions.length > 0 ? (
                  <datalist id="invoice-customer-options">
                    {customerOptions.map((option) => (
                      <option key={option} value={option} />
                    ))}
                  </datalist>
                ) : null}
              </div>
            </div>
            <div>
              <label
                htmlFor="invoice-create-number-preview"
                className="mb-1.5 block text-sm font-semibold text-gray-700 dark:text-gray-300"
              >
                Invoice Number
              </label>
              <Input
                id="invoice-create-number-preview"
                value={invoiceNumberPreview}
                disabled
                data-testid="accounting-ar-invoice-number-preview"
                className="bg-gray-100 dark:bg-gray-900"
              />
            </div>
            <div>
              <label
                htmlFor="invoice-create-date"
                className="mb-1.5 block text-sm font-semibold text-gray-700 dark:text-gray-300"
              >
                Invoice Date
              </label>
              <Input
                id="invoice-create-date"
                type="date"
                value={invoiceDate}
                data-testid="accounting-ar-invoice-date-input"
                onChange={(event) => setInvoiceDate(event.target.value)}
                className="bg-gray-50 dark:bg-gray-800"
              />
            </div>
            <div className="md:col-start-4">
              <label
                htmlFor="invoice-create-due-date"
                className="mb-1.5 block text-sm font-semibold text-gray-700 dark:text-gray-300"
              >
                Due Date
              </label>
              <Input
                id="invoice-create-due-date"
                type="date"
                value={dueDate}
                data-testid="accounting-ar-invoice-due-date-input"
                onChange={(event) => setDueDate(event.target.value)}
                className="bg-gray-50 dark:bg-gray-800"
              />
            </div>
          </div>

          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-bold uppercase tracking-wider text-gray-900 dark:text-white">
                Line Items
              </h3>
              <Button
                type="button"
                variant="ghost"
                className="gap-1 p-0 text-xs font-semibold text-indigo-600 hover:text-indigo-700"
                onClick={addLineItem}
                data-testid="accounting-ar-invoice-add-line-button"
              >
                <Plus className="h-4 w-4" />
                Add Line Item
              </Button>
            </div>

            <div className="overflow-hidden rounded-xl border border-gray-200 dark:border-gray-700">
              <TableShell
                columns={[
                  {
                    id: "product_or_service",
                    header: <>Product / Service</>,
                    cell: ({ row }) => (
                      <>
                        <Input
                          value={row.original.product_or_service}
                          data-testid={`accounting-ar-invoice-line-product-input-${row.original.id}`}
                          onChange={(event) =>
                            updateLineItem(
                              row.original.id,
                              "product_or_service",
                              event.target.value,
                            )
                          }
                          placeholder="Product or service"
                          className="border-none bg-transparent px-0 shadow-none"
                          list={`invoice-product-options-${row.original.id}`}
                        />
                        {productOptions.length > 0 ? (
                          <datalist
                            id={`invoice-product-options-${row.original.id}`}
                          >
                            {productOptions.map((option) => (
                              <option key={option} value={option} />
                            ))}
                          </datalist>
                        ) : null}
                      </>
                    ),
                    meta: {
                      headerClassName: "px-4 py-3 text-xs uppercase",
                      cellClassName: "px-4 py-3",
                    },
                  },
                  {
                    id: "description",
                    header: <>Description</>,
                    cell: ({ row }) => (
                      <Input
                        value={row.original.description}
                        data-testid={`accounting-ar-invoice-line-description-input-${row.original.id}`}
                        onChange={(event) =>
                          updateLineItem(
                            row.original.id,
                            "description",
                            event.target.value,
                          )
                        }
                        className="border-none bg-transparent px-0 shadow-none"
                      />
                    ),
                    meta: {
                      headerClassName: "px-4 py-3 text-xs uppercase",
                      cellClassName: "px-4 py-3",
                    },
                  },
                  {
                    id: "qty",
                    header: <>Qty</>,
                    cell: ({ row }) => (
                      <Input
                        type="number"
                        value={row.original.qty}
                        data-testid={`accounting-ar-invoice-line-qty-input-${row.original.id}`}
                        onChange={(event) =>
                          updateLineItem(
                            row.original.id,
                            "qty",
                            Number(event.target.value || "0"),
                          )
                        }
                        className="border-none bg-transparent px-0 text-center shadow-none"
                      />
                    ),
                    meta: {
                      headerClassName:
                        "px-4 py-3 text-center text-xs uppercase",
                      cellClassName: "px-4 py-3",
                    },
                  },
                  {
                    id: "price",
                    header: <>Price</>,
                    cell: ({ row }) => (
                      <Input
                        value={row.original.price}
                        data-testid={`accounting-ar-invoice-line-price-input-${row.original.id}`}
                        onChange={(event) =>
                          updateLineItem(
                            row.original.id,
                            "price",
                            event.target.value,
                          )
                        }
                        className="border-none bg-transparent px-0 text-right shadow-none"
                      />
                    ),
                    meta: {
                      headerClassName: "px-4 py-3 text-right text-xs uppercase",
                      cellClassName: "px-4 py-3",
                    },
                  },
                  {
                    id: "tax",
                    header: <>Tax (PPN)</>,
                    cell: ({ row }) => (
                      <Input
                        type="number"
                        min={0}
                        step="0.01"
                        value={row.original.tax.replace(/[^\d.-]/g, "")}
                        data-testid={`accounting-ar-invoice-line-tax-input-${row.original.id}`}
                        onChange={(event) =>
                          updateLineItem(
                            row.original.id,
                            "tax",
                            `${event.target.value}%`,
                          )
                        }
                        className="border-none bg-transparent px-0 text-right shadow-none"
                      />
                    ),
                    meta: {
                      headerClassName: "px-4 py-3 text-right text-xs uppercase",
                      cellClassName: "px-4 py-3",
                    },
                  },
                  {
                    id: "total",
                    header: <>Total</>,
                    cell: ({ row }) => {
                      const price =
                        Number(row.original.price.replaceAll(",", "")) || 0;
                      const taxPercent =
                        Number(row.original.tax.replace(/[^\d.-]/g, "")) || 0;
                      const rowTotal =
                        price * row.original.qty * (1 + taxPercent / 100);

                      return rowTotal.toLocaleString("id-ID");
                    },
                    meta: {
                      headerClassName: "px-4 py-3 text-right text-xs uppercase",
                      cellClassName:
                        "px-4 py-3 text-right text-sm font-bold text-gray-900 dark:text-white",
                    },
                  },
                  {
                    id: "actions",
                    header: "",
                    cell: ({ row }) => (
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        className="h-8 w-8 text-gray-400 hover:text-red-500"
                        onClick={() => removeLineItem(row.original.id)}
                        data-testid={`accounting-ar-invoice-line-remove-button-${row.original.id}`}
                        aria-label={`Remove line item ${row.original.id}`}
                      >
                        <Trash2 className="h-4 w-4" />
                      </Button>
                    ),
                    meta: {
                      headerClassName: "w-10 px-4 py-3",
                      cellClassName: "px-4 py-3 text-center",
                    },
                  },
                ]}
                data={lineItems}
                getRowId={(row) => row.id}
                headerClassName="bg-gray-50 dark:bg-gray-800/50"
                rowHoverable={false}
              />
            </div>
          </div>

          <div className="grid grid-cols-1 items-start gap-8 md:grid-cols-2">
            <div>
              <label
                htmlFor="invoice-create-notes"
                className="mb-2 block text-sm font-semibold text-gray-700 dark:text-gray-300"
              >
                Internal Notes
              </label>
              <Textarea
                id="invoice-create-notes"
                rows={3}
                value={notes}
                onChange={(event) => setNotes(event.target.value)}
                data-testid="accounting-ar-invoice-notes-textarea"
                placeholder="Add any notes for internal reference..."
                className="bg-gray-50 dark:bg-gray-800"
              />
            </div>

            <div className="space-y-3 md:ml-auto md:w-72">
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Subtotal</span>
                <span className="font-medium text-gray-900 dark:text-white">
                  Rp {totals.subtotal}
                </span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-gray-500">Tax (PPN 11%)</span>
                <span className="font-medium text-gray-900 dark:text-white">
                  Rp {totals.tax}
                </span>
              </div>
              <div className="flex justify-between border-t border-gray-200 pt-4 dark:border-gray-700">
                <span className="text-lg font-bold text-gray-900 dark:text-white">
                  Grand Total
                </span>
                <span className="text-2xl font-black text-indigo-600">
                  Rp {totals.grandTotal}
                </span>
              </div>
            </div>
          </div>

          <div className="flex items-center justify-end gap-3 border-t border-gray-200 pt-4 dark:border-gray-700">
            {errorMessage ? (
              <p
                className="mr-auto text-sm font-medium text-red-600"
                data-testid="accounting-ar-invoice-error-alert"
              >
                {errorMessage}
              </p>
            ) : null}
            <Button
              type="button"
              variant="ghost"
              onClick={onCancel}
              data-testid="accounting-ar-invoice-cancel-button"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isSubmitting}
              data-testid="accounting-ar-invoice-submit-button"
              className="bg-indigo-600 text-white hover:bg-indigo-700"
            >
              {submitLabel}
            </Button>
          </div>
        </CardContent>
      </Card>
    </form>
  );
}
