/** @format */

import type {
  AnalyticAccountCard,
  BudgetRow,
  CoaAccountRow,
  CurrencyRow,
  TaxRow,
} from "../types/settings";

export const SETTINGS_CARDS = [
  {
    key: "coa",
    title: "Chart of Accounts (COA)",
    description:
      "Management of the general ledger accounts structure, hierarchy, and types.",
    action_label: "Manage Accounts",
  },
  {
    key: "taxes",
    title: "Taxes",
    description:
      "Configuration for tax types, withholding rules, and rates (e.g., PPN 11%, PPh 23).",
    action_label: "Configure Taxes",
  },
  {
    key: "currencies",
    title: "Currencies",
    description: "Multi-currency support, automated exchange rates sync, and revaluation settings.",
    action_label: "Manage Currencies",
  },
  {
    key: "analytic-budgets",
    title: "Analytic & Budget",
    description: "Cost center management, analytic distribution rules, and budgeting tools.",
    action_label: "Configure Budgets",
  },
] as const;

export const COA_ROWS: CoaAccountRow[] = [
  {
    account_code: "10000",
    account_name: "Assets",
    account_type: "View",
    balance: "Rp 150,000,000",
    level: 0,
    is_group: true,
  },
  {
    account_code: "11000",
    account_name: "Current Assets",
    account_type: "Asset",
    balance: "Rp 45,000,000",
    level: 1,
    is_expanded: true,
  },
  {
    account_code: "11100",
    account_name: "Cash & Bank",
    account_type: "Bank & Cash",
    balance: "Rp 25,000,000",
    level: 2,
  },
  {
    account_code: "11101",
    account_name: "Bank BCA",
    account_type: "Bank",
    balance: "Rp 15,000,000",
    level: 3,
    is_highlighted: true,
  },
  {
    account_code: "11102",
    account_name: "Petty Cash",
    account_type: "Cash",
    balance: "Rp 10,000,000",
    level: 3,
  },
  {
    account_code: "11200",
    account_name: "Accounts Receivable",
    account_type: "Receivable",
    balance: "Rp 20,000,000",
    level: 2,
  },
  {
    account_code: "12000",
    account_name: "Fixed Assets",
    account_type: "Asset",
    balance: "Rp 105,000,000",
    level: 1,
  },
  {
    account_code: "20000",
    account_name: "Liabilities",
    account_type: "View",
    balance: "Rp 50,000,000",
    level: 0,
    is_group: true,
  },
  {
    account_code: "21000",
    account_name: "Current Liabilities",
    account_type: "Liability",
    balance: "Rp 50,000,000",
    level: 1,
    is_expanded: true,
  },
  {
    account_code: "21100",
    account_name: "Accounts Payable",
    account_type: "Payable",
    balance: "Rp 30,000,000",
    level: 2,
  },
  {
    account_code: "21200",
    account_name: "Tax Payable",
    account_type: "Current Liability",
    balance: "Rp 20,000,000",
    level: 2,
  },
  {
    account_code: "40000",
    account_name: "Income",
    account_type: "View",
    balance: "Rp 250,000,000",
    level: 0,
    is_group: true,
  },
  {
    account_code: "60000",
    account_name: "Expenses",
    account_type: "View",
    balance: "Rp 120,000,000",
    level: 0,
    is_group: true,
  },
];

export const TAX_ROWS: TaxRow[] = [
  {
    tax_id: "tax-1",
    tax_name: "PPN 11%",
    description: "VAT 11 Percent",
    tax_type: "Sales",
    rate_percent: "11.00%",
    tax_account: "210101 - PPN Keluaran",
    tax_account_description: "Short Term Liabilities",
    is_active: true,
  },
  {
    tax_id: "tax-2",
    tax_name: "PPN Masukan 11%",
    description: "Input VAT 11 Percent",
    tax_type: "Purchase",
    rate_percent: "11.00%",
    tax_account: "110501 - PPN Masukan",
    tax_account_description: "Current Assets",
    is_active: true,
  },
  {
    tax_id: "tax-3",
    tax_name: "PPh 23 Jasa",
    description: "Withholding Tax Service",
    tax_type: "Sales",
    rate_percent: "2.00%",
    tax_account: "210201 - Hutang PPh 23",
    tax_account_description: "Short Term Liabilities",
    is_active: false,
  },
  {
    tax_id: "tax-4",
    tax_name: "PPh 21 Pegawai",
    description: "Income Tax Employees",
    tax_type: "None",
    rate_percent: "0.00%",
    tax_account: "210202 - Hutang PPh 21",
    tax_account_description: "Short Term Liabilities",
    is_active: true,
  },
  {
    tax_id: "tax-5",
    tax_name: "VAT Exempt",
    description: "Non-Taxable Goods",
    tax_type: "Sales",
    rate_percent: "0.00%",
    tax_account: "210103 - VAT Exempt",
    tax_account_description: "Special Tax Account",
    is_active: true,
  },
];

export const CURRENCY_ROWS: CurrencyRow[] = [
  {
    currency_code: "IDR",
    symbol: "Rp",
    exchange_rate: "1.0000",
    last_updated: "Today, 09:00 AM",
    is_base: true,
    badge_class: "bg-red-100 text-red-700",
  },
  {
    currency_code: "USD",
    symbol: "$",
    exchange_rate: "15,450.0000",
    last_updated: "Today, 09:00 AM",
    is_base: false,
    badge_class: "bg-blue-100 text-blue-700",
  },
  {
    currency_code: "EUR",
    symbol: "€",
    exchange_rate: "16,820.5000",
    last_updated: "Yesterday, 04:30 PM",
    is_base: false,
    badge_class: "bg-yellow-100 text-yellow-700",
  },
  {
    currency_code: "SGD",
    symbol: "S$",
    exchange_rate: "11,540.2500",
    last_updated: "Yesterday, 04:30 PM",
    is_base: false,
    badge_class: "bg-orange-100 text-orange-700",
  },
  {
    currency_code: "JPY",
    symbol: "¥",
    exchange_rate: "105.4000",
    last_updated: "2 days ago",
    is_base: false,
    badge_class: "bg-indigo-100 text-indigo-700",
  },
];

export const BUDGET_ROWS: BudgetRow[] = [
  {
    budget_id: "budget-1",
    budget_name: "Q1 Marketing Campaign",
    department: "Marketing Dept",
    analytic_account: "MKT-001",
    period: "Jan 01, 2024 - Mar 31, 2024",
    target_amount: "$50,000.00",
    practical_amount: "$42,150.00",
    achievement_percent: 84,
    achievement_label: "84%",
    progress_class: "bg-green-500",
    achievement_class: "text-green-600 dark:text-green-400",
    avatar: "24",
    avatar_class: "bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400",
  },
  {
    budget_id: "budget-2",
    budget_name: "IT Infrastructure Upgrade",
    department: "Technology Dept",
    analytic_account: "TECH-002",
    period: "Jan 01, 2024 - Dec 31, 2024",
    target_amount: "$120,000.00",
    practical_amount: "$15,200.00",
    achievement_percent: 12,
    achievement_label: "12%",
    progress_class: "bg-indigo-500",
    achievement_class: "text-indigo-600 dark:text-indigo-400",
    avatar: "IT",
    avatar_class: "bg-orange-100 text-orange-600 dark:bg-orange-900/30 dark:text-orange-400",
  },
  {
    budget_id: "budget-3",
    budget_name: "Annual Training",
    department: "Human Resources",
    analytic_account: "HR-005",
    period: "Jun 01, 2024 - Dec 31, 2024",
    target_amount: "$35,000.00",
    practical_amount: "$2,100.00",
    achievement_percent: 6,
    achievement_label: "6%",
    progress_class: "bg-gray-400",
    achievement_class: "text-gray-600 dark:text-gray-400",
    avatar: "HR",
    avatar_class: "bg-red-100 text-red-600 dark:bg-red-900/30 dark:text-red-400",
  },
];

export const ANALYTIC_ACCOUNT_CARDS: AnalyticAccountCard[] = [
  {
    analytic_account_id: "anl-1",
    account_name: "Marketing Dept",
    reference_code: "MKT-001",
    current_balance: "-$42,150.00",
    active_budgets: 3,
    status: "Active",
    icon: "📣",
    icon_class: "bg-purple-100 text-purple-600 dark:bg-purple-900/30 dark:text-purple-400",
    balance_class: "text-red-600 dark:text-red-400",
  },
  {
    analytic_account_id: "anl-2",
    account_name: "Technology Dept",
    reference_code: "TECH-002",
    current_balance: "-$15,200.00",
    active_budgets: 5,
    status: "Active",
    icon: "🖥️",
    icon_class: "bg-blue-100 text-blue-600 dark:bg-blue-900/30 dark:text-blue-400",
    balance_class: "text-red-600 dark:text-red-400",
  },
  {
    analytic_account_id: "anl-3",
    account_name: "Human Resources",
    reference_code: "HR-005",
    current_balance: "-$2,100.00",
    active_budgets: 1,
    status: "Active",
    icon: "👥",
    icon_class: "bg-pink-100 text-pink-600 dark:bg-pink-900/30 dark:text-pink-400",
    balance_class: "text-red-600 dark:text-red-400",
  },
  {
    analytic_account_id: "anl-4",
    account_name: "Sales Dept",
    reference_code: "SLS-003",
    current_balance: "+$240,000.00",
    active_budgets: 2,
    status: "Active",
    icon: "🤝",
    icon_class: "bg-green-100 text-green-600 dark:bg-green-900/30 dark:text-green-400",
    balance_class: "text-green-600 dark:text-green-400",
  },
];

